device: "mps"  # "cuda", "mps", "cpu"

# Hyperparameters
train:
  batch_size: 32
  num_epochs: 2 # 30
  learning_rate: 0.0001
  patience: 3
  hidden_dim: 512

# Dataset
dataset:
  num_classes: 101
  val_split: 0.1
  backend_samples: 50
  base_dir: "dataset"
  image_dir: "dataset/images"
  meta_dir: "dataset/meta"
  train_file: "dataset/meta/train.txt"
  test_file: "dataset/meta/test.txt"
  classes_file: "dataset/meta/classes.txt"
  backend_dir: "dataset/backend_samples"

# Model outputs
output:
  model_checkpoint: "models/food_classification_model/checkpoints/test.pth"
  model_dir: "models/food_classification_model/checkpoints"
  plot_file: "resnet_50_model_test_2.png"
