name: CI - Test Model Accuracy

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - main

jobs:
  test-model:
    name: Model Accuracy Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9' 

      - name: Install CI requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          pip install dvc[s3]  # or dvc[gdrive], dvc[azure], etc., based on your remote

      - name: Configure DVC remote
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc remote add -d myremote s3://food101-nexdish-dvc-storage
          dvc remote modify myremote access_key_id $AWS_ACCESS_KEY_ID
          dvc remote modify myremote secret_access_key $AWS_SECRET_ACCESS_KEY
          dvc remote modify myremote region us-east-1
          dvc pull models/food_classification_model/checkpoints.dvc

      - name: Run Pytest
        run: |
          pytest tests/test_accuracy.py 
