name: Continuous Integration Pipeline

on:
  pull_request:
    branches:
      - main

jobs:
  test-fullstack:
    name: Full Stack + Model Accuracy Tests
    runs-on: ubuntu-latest
        
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

    services:
      docker:
        image: docker:24.0.5
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Set up CI dependencies
        run: |
          pip install -r tests/requirements.txt
          pip install dvc[s3]

      - name: Configure DVC remote
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          dvc remote add -d myremote s3://food101-nexdish-dvc-storage
          dvc remote modify myremote access_key_id $AWS_ACCESS_KEY_ID
          dvc remote modify myremote secret_access_key $AWS_SECRET_ACCESS_KEY
          dvc remote modify myremote region us-east-1
          dvc pull models/food_classification_model/checkpoints.dvc
          dvc pull models/outlier_detection_model/checkpoints.dvc

      - name: Build and Start Services
        run: |
          docker-compose up -d --build

      - name: Wait for services to be ready
        run: |
          for i in {1..30}; do
            curl -s http://localhost:8000/upload && break || sleep 2
          done

      - name: Run API and Accuracy Tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          pytest tests
